config/routes.rb
Rails.application.routes.draw do
  resources 'kittens'
  root 'kittens#index'
end

app/models/kitten.rb
class Kitten < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  def index
    @kittens = Kitten.all
    respond_to do |format|
      format.html
      format.xml {render :xml => @kittens}
      format.json {render :json => @kittens}
    end
  end
  def show
    @kitten = Kitten.find(params[:id])
    respond_to do |format|
      format.html
      format.xml {render :xml => @kitten}
      format.json {render :json => @kitten}
    end
  end
  def new
    @kitten = Kitten.new
  end
  def create
    kitten = Kitten.new
    kitten.name = params[:kitten][:name]
    kitten.cuteness = params[:kitten][:cuteness]
    kitten.softness = params[:kitten][:softness]
    kitten.age = params[:kitten][:age]
    kitten.save
    flash[:success] = "kitten created"
    redirect_to kitten
  end
  def edit
    @kitten = Kitten.find(params[:id])
  end
  def update
    kitten = Kitten.find(params[:id])
    kitten.update_attributes(name:params[:kitten][:name],
                             age:params[:kitten][:age],
                             cuteness:params[:kitten][:cuteness],
                             softness:params[:kitten][:softness])
   kitten.save
   flash[:success] = "kitten updated!"
   redirect_to kitten
  end
  def destroy
    kitten = Kitten.find(params[:id])
    kitten.delete
    flash[:success] = "kitten destroyed"
    redirect_to root_url
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_kitten_form.html.erb
<%= form_for @kitten do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :age %>
  <%= f.select :age, (1..25)%>
  <%= f.label :cuteness %>
  <%= f.select :cuteness, (1..10)%>
  <%= f.label :softness %>
  <%= f.select :softness, (1..10)%>
  <%= f.submit %>
<% end %>

app/views/kittens/edit.html.erb
<h1>Edit Kitten</h1>
<%= render "kitten_form" %>

app/views/kittens/index.html.erb
<h1>Look: here's a list of all the kittens</h1>
<ul>
  <% @kittens.each do |kitten| %>
    <li>
      <%= link_to kitten.name, kitten %>  | 
      <%= link_to "edit", edit_kitten_path(kitten) %>  |
      <%= link_to "destroy", kitten, method: "delete" %>
    </li>
  <% end %>
</ul>
<%= link_to "New Kitten", new_kitten_url %>

app/views/kittens/new.html.erb
<h1>new kitten</h1>
<%= render "kitten_form" %>

app/views/kittens/show.html.erb
<h1><%= @kitten.name %></h1>
<ul>
  <li>Cuteness: <%= @kitten.cuteness %></li>
  <li>Softness: <%= @kitten.softness %></li>
  <li>Age: <%= @kitten.age %></li>
</ul>

<ul>
  <li><%= link_to "edit kitten", edit_kitten_url %></li>
  <li><%= link_to "DESTROY kitten", @kitten, method: "delete" %> </li>  
  <li><%= link_to "back to index", root_url %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>KittensKittens</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% flash.each do |key, value| %>
  <%= content_tag :div, value, class: "flash #{key}" %>
<% end %>
<%= yield %>

</body>
</html>